#if !defined(_COMMENT_H)
#define _COMMENT_H

/**	Enum of possible comments between bots.
*/
enum Comment
{
	YES,
	NO,
	IM_IN,
	LETS_PLAY_HARD,
	HM,
	NICE_CATCH,
	BLUFF,
	MAKE_ME_A_SANDWICH,
	I_SEE_YOU_PREFER_THE_HARD_WAY,
	THATS_WHAT_SHE_SAID,
	YOU_SHOULD_HAVE_FOLDED_AT_THE_BEGINNING,
	WHAT_A_SHAME,
	A_LITTLE_BIT_OF_RAISE_HARMS_NONE,
	BET_YOUR_MOM_GETS_LAID_FOR_HALF_THE_POT_IM_GONNA_TAKE_NOW
};

#endif  //_COMMENT_H
